mode: deployment

image:
  repository: amazon/aws-otel-collector
  tag: latest
  pullPolicy: IfNotPresent

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
        - job_name: 'apache-web-server'
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: apache-web-server.*
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

  exporters:
    prometheusremotewrite:
      endpoint: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    awsemf:
      namespace: EKS/Apache
      region: ${AWS_REGION}

  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        exporters: [prometheusremotewrite, awsemf]
    telemetry:
      logs:
        level: debug
      metrics:
        address: 0.0.0.0:8888

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/eks-apache-web-server-adot-collector-role

ports:
  healthcheck:
    enabled: true
    containerPort: 13133
    servicePort: 13133
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888