apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache-web-server.fullname" . }}
  labels:
    app: {{ include "apache-web-server.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "apache-web-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "apache-web-server.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9117"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: apache
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      - name: apache-exporter
        image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
        imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
        args:
          - "--scrape_uri=http://localhost/server-status?auto"
        ports:
        - containerPort: 9117
          name: metrics
        resources:
          {{- toYaml .Values.exporter.resources | nindent 10 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "apache-web-server.fullname" . }}-config