apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-web-server.fullname" . }}-service
spec:
  selector:
    app: {{ include "apache-web-server.name" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
  - name: metrics
    port: 9117
    targetPort: 9117
  type: {{ .Values.service.type }}